### ISSUE TITLE
Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by PonyTang3** [aegypius/atom-php-fellow#1]
# **when i active it, atom shows the errors. How can i fix it.**

Error: Cannot find module 'bluebird'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\atom\App\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\atom\App\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/atom/Data/atom/packages/php-fellow/lib/namespace-guesser.coffee:1:29)
    at Object.<anonymous> (file:///C:/atom/Data/atom/packages/php-fellow/lib/namespace-guesser.coffee:1:1)
    at Module._compile (C:\atom\App\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee](C:atomAppAtomresourcesapp.asarsrccompile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\atom\App\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.module.exports.activate (file:///C:/atom/Data/atom/packages/php-fellow/lib/php-fellow.coffee:21:24)
    at Package.module.exports.Package.activateNow (C:\atom\App\Atom\resources\app.asar\src\package.js:183:20)
    at C:\atom\App\Atom\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\atom\App\Atom\resources\app.asar\src\package.js:92:15)
    at C:\atom\App\Atom\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\atom\App\Atom\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\atom\App\Atom\resources\app.asar\src\package-manager.js:538:21)
    at C:\atom\App\Atom\resources\app.asar\src\package-manager.js:342:19
    at C:\atom\App\Atom\resources\app.asar\src\config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (C:\atom\App\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\atom\App\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (C:\atom\App\Atom\resources\app.asar\src\config.js:816:29)
    at Config.module.exports.Config.setRawValue (C:\atom\App\Atom\resources\app.asar\src\config.js:608:19)
    at Config.module.exports.Config.set (C:\atom\App\Atom\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\atom\App\Atom\resources\app.asar\src\config.js:377:12)
    at Package.module.exports.Package.enable (C:\atom\App\Atom\resources\app.asar\src\package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\atom\App\Atom\resources\app.asar\src\package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (C:\atom\App\Atom\resources\app.asar\node_modules\settings-view\lib\package-card.js:328:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\atom\App\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\atom\App\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

**Comment by aegypius** [comment]
Thanks for your interest, this package is far for being published to atom package registry.  

You may have clone the repository so you may have to install dependencies manually using `npm`: 

```
cd C:/atom/Data/atom/packages/php-fellow 
npm install 
```

I have never tested this on Windows but you may already know how to do that. 

I plan to leave this package behind to contribute to [php-integrator-base suite](https://github.com/Gert-dev/php-integrator-base). You should definitively look at these package !

**Comment by PonyTang3** [comment]
I have solved this problem.But it didn't worked.When i pressed F4, it showed the error liked " Cannot read property 'psr-0' of undefined ".

**Comment by yoramdelangen** [comment]
Is this already in the php-intergrator-base suite?

**Comment by aegypius** [comment]
Not yet, I don't really have time to get it done for now.
